# Generated by Django 3.2 on 2021-11-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=10, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 's100_productspecification',
                'managed': False,
            },
        ),
    ]
