# Generated by Django 3.2 on 2021-11-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, db_column='agency_name', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=500, null=True)),
                ('phoneno', models.IntegerField()),
                ('contact_person', models.CharField(blank=True, db_column='contact_person', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
            ],
            options={
                'db_table': 's100_agencyinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, db_column='role_name', max_length=100, null=True)),
                ('restricted', models.CharField(blank=True, db_column='restricted', max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, db_column='active', null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 's100_role',
                'managed': False,
            },
        ),
    ]
