# Generated by Django 3.2 on 2021-11-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, db_column='file_name', max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
                ('file_size', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.CharField(blank=True, db_column='uploaded_by', max_length=100, null=True)),
                ('agency_name', models.CharField(blank=True, db_column='agency_name', max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 's100_fileinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Headerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(blank=True, db_column='product_line', max_length=100, null=True)),
                ('header_name', models.CharField(blank=True, max_length=100, null=True)),
                ('header_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 's100_header_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadatainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(blank=True, db_column='product_line', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 's100_file_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=10, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 's100_productspecification',
                'managed': False,
            },
        ),
    ]
